site_url: https://docs.lynway.org
site_name: Linway Docs
site_description: 'Linway project documentation'

# Настройка темы
theme:
  name: material
  language: en # Дефолтный язык интерфейса
  features:
    - navigation.tabs # Навигация в виде табов
    - navigation.sections # Секции в навигации
    - toc.integrate # Интегрировать оглавление страницы в навигацию
    - search.suggest # Подсказки при поиске
    - content.code.copy # Кнопка "копировать" для блоков кода
  # Настраиваем палитру и переключатель тем
  palette:
    - scheme: default # Светлая тема
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-7
        name: Переключиться на темную тему
    - scheme: slate # Темная тема
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-4
        name: Переключиться на светлую тему

# Секция для мультиязычности
extra:
  alternate:
    - name: Русский # Название в переключателе
      link: /ru/      # Ссылка на русскую версию
      lang: ru
    - name: English # Название в переключателе
      link: /en/      # Ссылка на английскую версию
      lang: en       # Код языка
    
plugins:
  - search
  - i18n:
      docs_structure: folder # Переключаем плагин в режим папок
      default_language: en
      languages: # ИСПРАВЛЕНО: теперь это список (с дефисами перед - locale)
        - locale: en
          name: English
          link: /en/
          build: true
          default: true
          # Навигация для английской версии (смотрит в docs/en/)
          nav:
            - Home: index.md
            - About: about.md
            
        - locale: ru
          name: Русский
          link: /ru/
          build: true
          # Навигация для русской версии (смотрит в docs/ru/)
          nav:
            - Главная: index.md
            - О проекте: about.md

# Расширения для Markdown
markdown_extensions:
  - admonition # Блоки !!! note, !!! warning
  - pymdownx.details # Сворачиваемые блоки
  - pymdownx.superfences # Вложенные блоки кода
  - pymdownx.tabbed: # Табы
      alternate_style: true
      
      
